//
// Created by ghisi on 09.10.22.
//

#ifndef AVR_MESSAGETYPE_H
#define AVR_MESSAGETYPE_H


enum MessageType {
    TIME_TICK,
    TIMER_STATE,
    DISPLAY_COMMAND,
    ASYNC_SCHEDULED,
    ASYNC_CHAIN_SCHEDULED,
    USER_INPUT,
    CLIMATE_REPORT,
    TEMPERATURE_CONTROL_COMMAND,
    TEMPERATURE_CONTROL_STATUS,
    MAX,
};


#endif //AVR_MESSAGETYPE_H
