//
// Created by ghisi on 09.10.22.
//

#ifndef AVR_MESSAGETYPE_H
#define AVR_MESSAGETYPE_H

#include <cstdint>

enum MessageType: uint8_t {
    TIME_TICK,
    TIMER_STATE,
    DISPLAY_COMMAND,
    ASYNC_SCHEDULED,
    ASYNC_CHAIN_SCHEDULED,
    USER_INPUT,
    CLIMATE_REPORT,
    TEMPERATURE_CONTROL_COMMAND,
    TEMPERATURE_CONTROL_STATUS,
    SERIAL_SEND,
    MEMORY_REPORT,
    CPU_REPORT,
    BUZZER,
    FAN_COMMAND,
    MAX,
};


#endif //AVR_MESSAGETYPE_H
